export const GET_CHART = 'GET_CHART';
export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING';
export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const CHANGE_DEFAULT_APP = 'CHANGE_DEFAULT_APP';

